spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bigchatbrasil
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: update  # ⚠️ TEMPORÁRIO: Vai dropar e recriar todas as tabelas
        show-sql: true
        properties:
            hibernate:
                format_sql: true

                id:
                    new_generator_mappings: true

jwt:



server:
  port: 8081





